{
 "title": "Market Dashboard",
 "time": { "from": "2019-09-16T00:00:00.000Z", "to": "2024-10-16T00:00:00.000Z" },
 "panels": [
  {
   "title": "Количество выполненных заказов для каждого клиента",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT c.name AS \"Client\", c.phone, COUNT(p.id) AS \"Purchases Count\"\nFROM Purchase p\nJOIN Client c ON p.clientID = c.id\nWHERE p.status = 'Выполнен'\nGROUP BY c.name, c.phone\nORDER BY \"Purchases Count\" DESC;"
    }
   ]
  },
  {
   "title": "Средняя стоимость продуктов по производителям",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT m.name AS \"Manufacturer\", AVG(pr.price) AS \"Average Price\"\nFROM Product pr\nJOIN Manufacturer m ON pr.manufacturerID = m.id\nGROUP BY m.name;\n"
    }
   ]
  },
  {
   "title": "Состояние заказов",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT p.status AS \"Status\", COUNT(p.id) AS \"Count\"\nFROM Purchase p\nGROUP BY p.status;\n"
    }
   ]
  },
  {
   "title": "Количество заказов по датам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT p.dateCreate AS \"Date\", COUNT(p.id) AS \"Purchases Count\"\nFROM Purchase p\nGROUP BY p.dateCreate\nORDER BY p.dateCreate;\n"
    }
   ]
  },
  {
   "title": "Заказы",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT p.id AS \"Purchase ID\", c.name AS \"Client\", s.name AS \"Store\", pr.name AS \"Product\", p.productCount AS \"Product Count\", p.status, p.dateCreate AS \"Date\"\nFROM Purchase p\nJOIN Client c ON p.clientID = c.id\nJOIN Store s ON p.storeID = s.id\nJOIN Product pr ON p.productID = pr.id;\n"
    }
   ]
  }
 ]
}